162 move the repository module of the mediator coordination crate to a separate crate
adorsys/didcomm-mediator-rs pull request #170
Opened 2024-09-12 16:04 UTC by ndefokou

@Hermann-Core @IngridPuppet Please review this PR

2024-09-13 12:53 UTC, Hermann-Core commented
Please ensure you are up to date with the **main** branch before requesting again. There’re conflicts.

2024-09-16 12:12 UTC, Hermann-Core requested changes

2024-09-16 12:18 UTC, Hermann-Core commented on crates/plugins/mediator-coordination/src/web/handler.rs
> +            message_repository: Arc::new(MockMessagesRepository::from(vec![])), // Merged from origin
@ndefokou check at the manifest file and remove all the unused dependencies. 
https://github.com/adorsys/didcomm-mediator-rs/blob/35bc4f2185db4638a4f0c6d9ee67275e23d89a14/crates/database/Cargo.toml#L6-L25
The **`[feature]`** and **`[dev-dependencies]`** sections are not needed. Delete them.
https://github.com/adorsys/didcomm-mediator-rs/blob/35bc4f2185db4638a4f0c6d9ee67275e23d89a14/crates/database/Cargo.toml#L27-L37

2024-09-16 14:11 UTC, IngridPuppet commented on crates/database/src/lib.rs
> +pub trait Entity: Sized + Serialize {}
Hey @Hermann-Core - It is a shared abstraction for all the objects to store in MongoDB collections. It helps constrain a set of operations to implement for associated repositories.

2024-09-16 14:44 UTC, IngridPuppet commented on crates/database/src/lib.rs
> +pub trait Entity: Sized + Serialize {}
Fine then.

2024-09-16 15:10 UTC, ndefokou commented on crates/did-utils/examples/ed25519-sign.rs
> +    Ed25519KeyPair, {CoreSign, Generate},
I am not working with this file i did a `cargo fmt` on the entire project

2024-09-16 16:09 UTC, Hermann-Core approved these changes

2024-09-16 16:11 UTC, merged