202 rename directory from mediator coordination to didcomm messaging
adorsys/didcomm-mediator-rs pull request #215
Opened 2024-10-14 15:27 UTC by ndefokou

@Christiantyemele @Hermann-Core

2024-10-14 15:45 UTC, Christiantyemele requested changes

2024-10-14 15:45 UTC, Christiantyemele commented on Cargo.toml
>      "crates/plugins/oob-messages",
```didcomm``` double m

2024-10-15 09:35 UTC, Christiantyemele approved these changes

2024-10-15 09:36 UTC, Christiantyemele commented
@ndefokou you have unresolve conflicts

2024-10-15 10:23 UTC, Christiantyemele approved these changes

2024-10-15 10:30 UTC, merged

2024-10-15 11:50 UTC, Hermann-Core commented
The directory **didcomm-messaging** should be located within the **web-plugins** folder. The **plugin** prefix you've included is unnecessary, as its presence within the **web-plugins** folder already indicates that it is a web plugin.