Detailed guide on DIDComm messaging for edge device registration and …
adorsys/didcomm-mediator-rs pull request #234
Opened 2024-11-06 11:37 UTC by Tekum-Emmanuella

…OOB message exchange.

2024-11-06 11:52 UTC, Christiantyemele commented
@Tekum-Emmanuella Please can you give a description to this issue

2024-11-06 12:24 UTC, Christiantyemele requested changes

2024-11-06 12:24 UTC, Christiantyemele commented on docs/edge-device-doc.md
> +With the growth of IoT and connected devices, ensuring secure, private communication between edge devices—like smart sensors, appliances, and mobile devices—has become essential. DIDComm (Decentraliz
**DIDComm provides a protocol for private, out-of-band (OOB) messaging** does didcomm really provides a and out of band messaging way ? It's important to initiate a didcomm communication but didcomm does not provides a way for this to be done

2024-11-08 14:57 UTC, chendiblessing approved these changes

2024-11-11 11:37 UTC, Christiantyemele requested changes

2024-11-11 11:37 UTC, Christiantyemele commented on docs/edge-device-doc.md
> +Secure Key Exchange: Alice and the Mediator exchange public keys, establishing the foundation for encrypted communication.
you have to say how alice and the mediator exchange their keys

2024-11-11 11:37 UTC, Christiantyemele commented on docs/edge-device-doc.md
> +* **Acknowledgment:** Bob decrypts and reads Alice’s message, then sends an acknowledgment back to confirm delivery.
it think what you meant is bob prepares a message for a alice, bob cannot receive message here it has no connection with the mediator so far and you have to tell how it is possible for bob to send message to alice through the mediator

2024-11-12 15:04 UTC, ndefokou approved these changes
Good :+1:

2024-11-13 09:10 UTC, Blindspot22 approved these changes
LGTM :rocket:

2024-11-13 14:56 UTC, Christiantyemele approved these changes

2024-11-14 08:25 UTC, merged