231 discover feature protocol
adorsys/didcomm-mediator-rs pull request #236
Opened 2024-11-06 14:50 UTC by Christiantyemele

2024-11-06 14:51 UTC, Christiantyemele commented
> _ No description provided. _

2024-11-11 10:36 UTC, Hermann-Core commented
> As from the spec [here:](https://didcomm.org/discover-features/2.0/) we will need to have a way to know in real time what protocols our mediator supports and is willing to disclose, From our previous disscussion i think we brought out a way which could help, were we said the protocols will be loaded in a hashmap, i thought of search for the protocols to disclosed in that hashmap, I am not a 100% sure its the best way to it but for now its the only way i see, But i will need to collaborate with @Hermann-Core and @ndefokou if that be the case. 

Protocols should be separate and not directly communicate with each other. We need a method to identify supported protocols. Currently, we have a couple of solutions:
* Reading the manifest file of the **didcomm-messaging** plugin to get the declared features, although:
  * It doesn't provide the versions of the supported protocols.
  * Some protocols may be intentionally omitted during the loading of the mediator server.
* Adding the collected protocols into the **`AppState`**, thus, the handler can access and identify the mounted protocols.

2024-11-11 14:23 UTC, Blindspot22 requested changes
I will approve these after the conflicts have been solved.

2024-11-14 03:00 UTC, Blindspot22 approved these changes

2024-11-19 11:05 UTC, Hermann-Core requested changes

2024-11-19 11:05 UTC, Hermann-Core commented on crates/web-plugins/didcomm-messaging/protocols/discover-features/src/handler.rs
> +}
Please include additional test scenarios, such as various message types from the same protocol (to verify that only the protocols are returned and only once), queries that do not match the supported protocols, bad requests, unsupported **feature-type** to see if your code behaves as expected.

2024-11-19 11:06 UTC, Hermann-Core commented on crates/web-plugins/didcomm-messaging/protocols/discover-features/src/handler.rs
> +                                                disclosed_protocols.insert(id.to_string());
What are you trying to do here?

2024-11-25 09:53 UTC, Hermann-Core commented on crates/web-plugins/didcomm-messaging/protocols/discover-features/src/handler.rs
> +            Some(repository),
You can simply enter the `None` parameter if you are not using the App repository.

2024-11-25 09:56 UTC, Hermann-Core commented
Please merge the main branch to yours.

2024-11-25 10:31 UTC, Hermann-Core approved these changes

2024-11-25 10:32 UTC, merged