Intergration env support
adorsys/didcomm-mediator-rs pull request #283
Opened 2024-12-05 14:03 UTC by Christiantyemele

2024-12-06 09:11 UTC, Christiantyemele commented
Suggested edit:
```diff
diff --git a/.env b/.env
index e2af3f8..2952ea7 100644
--- a/.env
+++ b/.env
@@ -2,4 +2,4 @@ SERVER_PUBLIC_DOMAIN="http://didcomm-mediator.com"
 SERVER_LOCAL_PORT="8080"
 STORAGE_DIRPATH="crates/generic-server/target/storage"
 MONGO_DBN="mediator-coordination"
-MONGO_URI="mongodb://0.0.0.0:27017"
+MONGO_URI="mongodb://localhost:27017"

```

2024-12-20 10:27 UTC, Blindspot22 approved these changes
Great :+1: good to go.
I think, you should squash some of the commits into a single commit or segment, because some of them don't make sense individually and a couple of repetitions.
e.g 12 commits bearing the same name :)

2024-12-20 10:28 UTC, ndefokou commented
Fixed the conflicts and after that i will approve the ticket

2025-01-09 14:26 UTC, Hermann-Core requested changes

2025-01-09 14:26 UTC, Hermann-Core commented on Dockerfile
> +    cp target/release/didcomm-mediator /usr/local/bin/didcomm-mediator
Please leverage [build caching](https://docs.docker.com/build/cache/optimize/) to speed up the build process. I also suggest using the alpine version of the builder image as it will enable us to easily construct the final application image with an alpine base, resulting in the lowest possible image size.

2025-01-09 14:26 UTC, Hermann-Core commented on Dockerfile
> +ENTRYPOINT ["didcomm-mediator"]
As mentioned in the previous comment, we could use the Alpine image as our application base image. Additionally, it is advisable to create a new non-privileged user for the application to run under for security purposes.

2025-01-09 14:26 UTC, Hermann-Core commented on docker-compose.yml
> +version: "3.8"
`version` is now deprecated. remove it to suppress the warning.
https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

2025-01-09 14:26 UTC, Hermann-Core commented on docker-compose.yml
> +      - mongodb
better
```suggestion
    depends_on:
      mongodb:
        condition: service_healthy
```

2025-01-09 14:26 UTC, Hermann-Core commented on docker-compose.yml
> +
Add a health check condition to ensure the service is ready to work.
e.g.
```yaml
    healthcheck:
      test: ["CMD", "mongo", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5
```

2025-01-09 14:26 UTC, Hermann-Core commented on docker-compose.yml
> +  mongo-data:
I do not see where you define secrets. Does this imply that the database will be accessed without any protection?

2025-01-09 14:43 UTC, IngridPuppet commented on .gitignore
> -.env
I'm tired of PRs changing this logic 🤦 Also note that `.env.example` SHOULD be visible, i.e., removed from `.gitignore`.

2025-01-09 16:22 UTC, Christiantyemele commented on .dockerignore
> +.idea/
okay

2025-01-09 16:22 UTC, Christiantyemele commented on .gitignore
> -.env
okay

2025-01-10 09:40 UTC, Christiantyemele commented on docker-compose.yml
> +version: "3.8"
ok

2025-01-10 09:53 UTC, Christiantyemele commented on docker-compose.yml
> +  mongo-data:
true its an issue

2025-01-10 10:43 UTC, Hermann-Core commented on .gitignore
> -.env
> I'm tired of PRs changing this logic 🤦 Also note that `.env.example` SHOULD be visible, i.e., removed from `.gitignore`.

Could you tell why the `.env.example` should be visible ? I think we don’t need it anymore

2025-01-21 10:52 UTC, chendiblessing approved these changes

2025-01-27 21:02 UTC, stephane-segning requested changes
It's missing, the storage path in the deployment. There should be a PVC there.

2025-01-29 07:25 UTC, Christiantyemele commented
> It's missing, the storage path in the deployment. There should be a PVC there.

where do you mean?, cause there is a pvc in the database deployment which is the only service requiring a storage medium ?

2025-01-29 07:30 UTC, Christiantyemele commented on mediator-charts/templates/mongodb-deployment.yaml
> Please use https://artifacthub.io/packages/helm/bitnami/mongodb instead of rewriting the mongo deployment files.

2025-01-29 07:30 UTC, Christiantyemele commented on mediator-charts/templates/mongodb-deployment.yaml
> Please use https://artifacthub.io/packages/helm/bitnami/mongodb instead of rewriting the mongo deployment files.

i don't see the issue with the mongo deployment files since they are already written and works fine

2025-01-29 07:41 UTC, Christiantyemele commented on mediator-charts/templates/secrets.yaml
i though this file will stored in a special way ?, cause even reading from and env file, the secrets are still in text form there

2025-01-30 21:30 UTC, stephane-segning commented on mediator-charts/templates/mongodb-deployment.yaml
The problem is the fact, that you might make mistakes. Bitnami are known for the quality of their work. Please don't reinvent the wheel.

2025-01-30 21:32 UTC, stephane-segning commented on mediator-charts/templates/secrets.yaml
Reading from the env is still in clear text, sure. But env are in the machine already. So we secure the access to the machine and ensure we cannot have those secrets through any other way.

2025-01-30 21:33 UTC, stephane-segning commented
> > It's missing, the storage path in the deployment. There should be a PVC there.
> 
> where do you mean?, cause there is a pvc in the database deployment which is the only service requiring a storage medium ?

Yeah, so the mediator write in `.txt` the content of the DID. Right? So, what happens if a pod restarts?

2025-01-30 21:39 UTC, stephane-segning requested changes

2025-01-30 21:39 UTC, stephane-segning commented on Dockerfile
> +COPY .env .env
Do you want to have a .env into your image? Why not leverage env variables?

2025-01-31 14:36 UTC, Christiantyemele commented
> It's missing, the storage path in the deployment. There should be a PVC there.

exact

2025-02-04 09:24 UTC, Hermann-Core requested changes

2025-02-04 09:24 UTC, Hermann-Core commented on Dockerfile
> +    cp target/release/didcomm-mediator /usr/local/bin/didcomm-mediator
No. it is not supposed to bring troubles. It is supposed to leverage caches to speed up the build process.

2025-02-04 09:24 UTC, Hermann-Core commented on Dockerfile
> +FROM ubuntu:22.04
An image of 200MB just to run our application is too large. We can get really light images by statically linked our executable (e.g. using the **musl libc** or **crt-static** `rustc` feature) and base images such as `FROM scratch`,  `Distroless` or `alpine`.

2025-02-04 09:24 UTC, Hermann-Core commented on docker-compose.yml
> +      #   condition: service_healthy
Why have you commented out the condition?

2025-02-04 09:24 UTC, Hermann-Core commented on docker-compose.yml
> +    #   retries: 5
Why have you commented out the service healthcheck?

2025-02-06 14:51 UTC, Christiantyemele commented on Dockerfile
> +COPY .env .env
I did this when i how the deployment would look like but i guest its not usefull again

2025-02-06 14:52 UTC, Christiantyemele commented on Dockerfile
> +FROM ubuntu:22.04
i refactor the final image to 33.4MB :+1:

2025-02-06 14:56 UTC, Christiantyemele commented on docker-compose.yml
> +    #   retries: 5
fixed

2025-02-06 14:57 UTC, Christiantyemele commented on docker-compose.yml
> +      #   condition: service_healthy
fixed

2025-02-06 14:57 UTC, Christiantyemele commented on mediator-charts/templates/mongodb-deployment.yaml
okay

2025-02-06 14:57 UTC, Christiantyemele commented on mediator-charts/templates/secrets.yaml
the secrets are now kept on aws secret manager

2025-02-07 06:26 UTC, stephane-segning reviewed
Good work. At last, I have some questions about the Dockerfile. How come we have into it the x86 only? It means if I built on top of a Mac Processor, I won't be capable of building ?

2025-02-12 07:32 UTC, Christiantyemele commented on Dockerfile
> +RUN cargo build --release --target x86_64-unknown-linux-musl && \
yh this is not something we want

2025-02-12 07:43 UTC, Christiantyemele commented
@Hermann-Core as for using mount-binds and mount-cache to increase build time of the image i found some difficulties doing that but i think it should not be a reason for this ticket to stay open any longer as it only increase image build time, we can create a refactoring issue for that in future, this is suggestion on this.

2025-02-12 08:31 UTC, stephane-segning approved these changes

2025-02-12 08:38 UTC, ndefokou approved these changes
Good :+1:

2025-02-12 11:56 UTC, Hermann-Core approved these changes

2025-02-12 13:13 UTC, merged