Documentation of the generic-server
adorsys/didcomm-mediator-rs pull request #93
Opened 2024-06-26 11:24 UTC by ndefokou

@francis-pouatcha @IngridPuppet

2024-06-26 14:39 UTC, Hermann-Core reviewed
There are typos in the documentation. Please review the file again and correct them.

2024-06-26 15:18 UTC, ndefokou commented
@Hermann-Core typos corrected

2024-06-26 15:57 UTC, Hermann-Core reviewed
I suggest compacting the content a bit. Focus on the most important information and summarize where possible, when appropriate, add external links for further reading instead of including lengthy explanations. This will keep the documentation concise and provide additional resources for those who want to dive deeper.

2024-06-26 16:12 UTC, IngridPuppet requested changes
Check my review of #91. Your documentation seems more focused on what a generic server is in general, and this is not the right place to have such lecture. One is rather interested in what this generic server implementation has to offer.

2024-06-27 10:00 UTC, ndefokou commented
@IngridPuppet @Hermann-Core, please check the improvement I did.

2024-07-01 13:18 UTC, ndefokou commented on generic-server/README.md
> +
@Hermann-Core  Please review this again.

2024-07-01 13:20 UTC, ndefokou commented
@Hermann-Core  Please review this again.

2024-07-09 10:27 UTC, IngridPuppet requested changes

2024-07-09 10:27 UTC, IngridPuppet commented on generic-server/README.md
> +- Ensure the plugin container is re-initialized to include the new plugin.**
This step is not necessary, the plugins are loaded automatically as the server boots. I can't recall the plugin container being able to be re-initialized.

2024-07-09 10:27 UTC, IngridPuppet commented on generic-server/README.md
> +- Add the plugin to the static PLUGINS array.
Improve the styling:
- Use conventional markdown numbered lists.
- There is no need to define a list when you only have one item. For example, I'm using a list to make suggestions here 'cause I have at least two of them.
- Preview your markdown code. You can use a live editor such as https://dillinger.io/.
<br>

```suggestion

**1. Implement the `Plugin` Trait:**

Define the necessary methods (e.g., name(), mount(), and routes()).

**2. Register the Plugin:**

Add the plugin to the static PLUGINS array.
```

2024-07-09 10:27 UTC, IngridPuppet commented on generic-server/README.md
> +- Add the plugin to the static PLUGINS array.
Indicate where to find that array.

2024-07-09 14:20 UTC, IngridPuppet requested changes

2024-07-09 14:20 UTC, IngridPuppet commented on generic-server/README.md
> + Add the plugin to the static PLUGINS array.This array are located in your main server configuration file or a central location where the server initializes and manages plugins.
```suggestion
 Add the plugin to the static PLUGINS array (located in `src/plugin/mod.rs`).
```

2024-07-09 14:37 UTC, IngridPuppet approved these changes

2024-07-10 10:41 UTC, Hermann-Core requested changes

2024-07-10 10:41 UTC, Hermann-Core commented on generic-server/README.md
> +```
Maybe you can also add another example here showing how the plugin can be added to the static `PLUGINS` array ?

2024-07-10 10:41 UTC, Hermann-Core approved these changes

2024-07-11 10:45 UTC, Hermann-Core approved these changes

2024-07-11 10:46 UTC, merged